remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-remote-theme
title: other-notes
description: Miscellaneous notes
social-network-links:
  - email: roopnc1@mcmaster.ca
  - rss: true
  - github: Hextical
  - linkedin: cameron-roopnarine
  